spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerceapp15
    username: postgres
    password: 2@5a!3b2
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

    jpa.show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      springframework=DEBUG: